//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insert_Update_Delete_View_Search_in_Csharp_SQL_Server_Database__18_11_2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id { get; set; }
        public string sname { get; set; }
        public string sadd { get; set; }
        public Nullable<int> phone { get; set; }
        public Nullable<int> sem { get; set; }
        public string branch { get; set; }
    }
}
