//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsExercise_05_10_2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int id { get; set; }
        public int Code { get; set; }
        public string Fullname { get; set; }
        public bool Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int>PhoneNumber { get; set; }
        public string Class { get; set; }
        public string Email { get; set; }
        public string LivingAddress { get; set; }
    }
}
