//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Family_Members_Information_15_11_2019
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FamilyMembersManagementEntities : DbContext
    {
        public FamilyMembersManagementEntities()
            : base("name=FamilyMembersManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        internal object GetClass()
        {
            throw new NotImplementedException();
        }

        public virtual DbSet<member> members { get; set; }
    }
}
